# Appveyor.yml file to build installer packages for eclipse

skip_tags: true

configuration: Release

image: Visual Studio 2015

environment:
  EclipseRelease: neon.3
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

  matrix:
    - EclipseDistribution: CDT
#    - EclipseDistribution: PDE

before_build:
  - ps: build\SetVersionInfo.ps1
  - ps: nuget.exe restore -NonInteractive EclipseInstaller.sln

build_script:
  - ps: mvn -P com.tridigee.$($env:EclipseDistribution.toLower()) clean verify
  - ps: msbuild setup\Eclipse$($env:EclipseDistribution)\Eclipse$($env:EclipseDistribution)_x86.wixproj /p:Platform=x86
  - ps: msbuild setup\Eclipse$($env:EclipseDistribution)\Eclipse$($env:EclipseDistribution)_x64.wixproj /p:Platform=x64

artifacts:
  - path: deploy\$(Configuration)\Eclipse$(EclipseDistribution)-*.msi
