# Appveyor.yml file to build installer packages for eclipse

skip_tags: true

platform:
  - x64
  - x86

configuration: Release

environment:
  EclipseRelease: neon.2
  EclipseDistribution: cpp

before_build:
  - ps: nuget.exe restore -NonInteractive EclipseInstaller.sln
  - ps: build\DownloadEclipse.ps1

build:
  project: setup\EclipseCDT\EclipseCDT.wixproj

artifacts:
  - path: setup\EclipseCDT\bin\$(Platform)\$(Configuration)\*.msi
