# Appveyor.yml file to build installer packages for eclipse

skip_tags: true

platform:
  - x64
  - x86

configuration: Release

environment:
  EclipseRelease: neon.2

  matrix:
    - EclipseDistribution: CDT
    - EclipseDistribution: PDE

before_build:
  - ps: build\SetVersionInfo.ps1
  - ps: nuget.exe restore -NonInteractive EclipseInstaller.sln
  - ps: build\DownloadEclipse.ps1

build:
  project: setup\Eclipse$(EclipseDistribution)\Eclipse$(EclipseDistribution).wixproj

artifacts:
  - path: setup\Eclipse$(EclipseDistribution)\bin\$(Platform)\$(Configuration)\*.msi
