# Appveyor.yml file to build installer packages for eclipse

skip_tags: true

platform: x64

configuration: Release

before_build:
  - ps: nuget.exe restore -NonInteractive EclipseInstaller.sln
  - ps: build\DownloadEclipse.ps1 -Version neon-2 -Distribution cpp -Architecture $env:Platform

build:
  project: setup\EclipseCDT\EclipseCDT.wixproj

artifacts:
  - path: setup\EclipseCDT\bin\$(Platform)\$(Configuration)\*.msi
