# Appveyor.yml file to build installer packages for eclipse

skip_tags: true

configuration: Release

environment:
  EclipseRelease: neon.2

  matrix:
    - EclipseDistribution: CDT
    - EclipseDistribution: PDE

before_build:
  - ps: build\SetVersionInfo.ps1
  - ps: nuget.exe restore -NonInteractive EclipseInstaller.sln
  - ps: build\DownloadEclipse.ps1 -Architecture x86
  - ps: build\DownloadEclipse.ps1 -Architecture x64

build_script:
  - ps: msbuild setup\Eclipse$($env:EclipseDistribution)\Eclipse$($env:EclipseDistribution).wixproj /p:Platform=x86
  - ps: msbuild setup\Eclipse$($env:EclipseDistribution)\Eclipse$($env:EclipseDistribution).wixproj /p:Platform=x64

artifacts:
  - path: setup\Eclipse$(EclipseDistribution)\bin\*\$(Configuration)\*.msi
